# -*- mode: ruby -*-
# vi: set ft=ruby :

$installJava = <<SCRIPT
echo "******* installing java jdk"

yum install java-1.8.0-openjdk-devel -y

SCRIPT

$updateJava = <<SCRIPT

mv /tmp/setJavaHome.sh /etc/profile.d/setJavaHome.sh

chmod a+x /etc/profile.d/setJavaHome.sh

sudo unzip -o -j -q /tmp/jce_policy-8.zip -d $JAVA_HOME/jre/lib/security/

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"

  config.vm.box_check_update = true

  config.vbguest.auto_update = true

  config.vbguest.no_remote = true

  config.vbguest.no_install = false

  config.vm.provision "installJava", type:  "shell", inline: $installJava

  config.vm.provision "base", type: "shell", path: "provision-base.sh"

  config.vm.provision "file", source: "setJavaHome.sh", destination: "/tmp/setJavaHome.sh"

  config.vm.provision "file", source: "jce_policy-8.zip", destination: "/tmp/jce_policy-8.zip"

  config.vm.provision "updateJava", type:  "shell", inline: $updateJava

end