HOSTNAME = "secure.hdp.local"
IP = "192.168.66.101"

$hostsFile = <<SCRIPT
cat > /etc/hosts <<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

$1  $2
EOF
SCRIPT

$installJava = <<SCRIPT
echo "installing java jdk..."

yum install java-1.7.0-openjdk-devel -y -q

echo "exporting path variables..."

echo "export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75.x86_64" >> /home/vagrant/.bashrc
echo "PATH=$JAVA_HOME/bin:$PATH" >> /home/vagrant/.bashrc

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-6.6"

  config.vm.box_check_update = false

  config.vm.provision "hosts", type:  "shell", inline: $hostsFile, args: [IP, HOSTNAME]

  config.vm.provision "java", type:  "shell", inline: $installJava

  config.vm.provision "base", type: "shell", path: "provision-base.sh"

  config.vm.provision "ambari", type: "shell", path: "provision-ambari.sh", args: [HOSTNAME]

  config.vm.provision "cluster", type: "shell", path: "provision-cluster.sh", args: [HOSTNAME]

  config.vm.provision "ranger", type: "shell", path: "provision-ranger.sh", args: [HOSTNAME]

  config.vm.hostname = HOSTNAME

  config.vm.network "private_network", ip: IP

  config.multihostsupdater.aliases = {IP => [HOSTNAME]}

  config.vbguest.no_remote = true

  config.vbguest.no_install = true

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
    v.name = HOSTNAME
  end
end