# -*- mode: ruby -*-
# vi: set ft=ruby :

$installJava = <<SCRIPT
echo "******* installing java jdk"

yum install java-1.7.0-openjdk-devel -y -q

echo "******* exporting path variables"

echo "export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75.x86_64" >> /home/vagrant/.bashrc
echo "PATH=$JAVA_HOME/bin:$PATH" >> /home/vagrant/.bashrc

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-6.6"

  config.vm.box_check_update = true

  config.vbguest.auto_update = true

  config.vbguest.no_remote = true

  config.vbguest.no_install = false

  config.vm.provision "java", type:  "shell", inline: $installJava

  config.vm.provision "base", type: "shell", path: "provision-base.sh"

end